// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneSecurity.Server.Data;

#nullable disable

namespace OneSecurity.Server.Migrations
{
    [DbContext(typeof(LocalAgentDbContext))]
    [Migration("20260709072437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("OneSecurity.Server.Models.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardwareSpecs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("Status");

                    b.ToTable("agents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "agent-win-his-01",
                            ConfigId = 1L,
                            Hostname = "DESKTOP-FC9F6G9",
                            IpAddress = "192.168.1.35",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Windows Server 2022",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        },
                        new
                        {
                            Id = "agent-lnx-db-01",
                            ConfigId = 1L,
                            Hostname = "ubuntu-hosp-a-db",
                            IpAddress = "192.168.1.40",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Ubuntu 22.04 LTS",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        },
                        new
                        {
                            Id = "agent-win-app-01",
                            ConfigId = 1L,
                            Hostname = "win-hosp-a-app",
                            IpAddress = "192.168.1.41",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Windows Server 2019",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        },
                        new
                        {
                            Id = "agent-win-his-02",
                            ConfigId = 1L,
                            Hostname = "win-hosp-b-his",
                            IpAddress = "192.168.1.50",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Windows Server 2022",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        },
                        new
                        {
                            Id = "agent-lnx-web-02",
                            ConfigId = 1L,
                            Hostname = "ubuntu-hosp-b-web",
                            IpAddress = "192.168.1.51",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Ubuntu 20.04 LTS",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        });
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AgentConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartbeatIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonitoredLogsConfig")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeartbeatIntervalSeconds = 10,
                            IsDefault = true,
                            MetricsIntervalSeconds = 30,
                            MonitoredLogsConfig = "[]",
                            Name = "Default Hospital Policy",
                            UpdatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        });
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelegramSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TriggerEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RuleId");

                    b.HasIndex("TriggerEventId");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AlertRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertSeverity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "EventType");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.MetricRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CpuUsagePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiskUsagePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("NetworkInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetworkOutBytes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RamUsagePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AgentId", "Timestamp")
                        .HasDatabaseName("IX_metric_records_agent_timestamp_desc");

                    b.ToTable("metric_records", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.SecurityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Severity");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AgentId", "Timestamp")
                        .HasDatabaseName("IX_security_events_agent_timestamp_desc");

                    b.ToTable("security_events", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Agent", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.AgentConfig", "Config")
                        .WithMany("Agents")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Config");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Alert", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.Agent", "Agent")
                        .WithMany("Alerts")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSecurity.Server.Models.AlertRule", "Rule")
                        .WithMany("Alerts")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneSecurity.Server.Models.SecurityEvent", "TriggerEvent")
                        .WithMany()
                        .HasForeignKey("TriggerEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agent");

                    b.Navigation("Rule");

                    b.Navigation("TriggerEvent");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.MetricRecord", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.Agent", "Agent")
                        .WithMany("MetricRecords")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.SecurityEvent", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.Agent", "Agent")
                        .WithMany("SecurityEvents")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Agent", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("MetricRecords");

                    b.Navigation("SecurityEvents");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AgentConfig", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AlertRule", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
