// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneSecurity.Server.Data;

#nullable disable

namespace OneSecurity.Server.Migrations
{
    [DbContext(typeof(LocalAgentDbContext))]
    partial class LocalAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Capabilities")
                        .HasColumnType("TEXT");

                    b.Property<string>("CollectorVersion")
                        .HasColumnType("TEXT");

                    b.Property<long>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardwareSpecs")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportedActions")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("Status");

                    b.ToTable("agents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "agent-win-his-01",
                            AssetId = 1L,
                            ConfigId = 1L,
                            HospitalId = 1,
                            Hostname = "DESKTOP-FC9F6G9",
                            IpAddress = "192.168.1.35",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Windows Server 2022",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        },
                        new
                        {
                            Id = "agent-lnx-db-01",
                            AssetId = 2L,
                            ConfigId = 1L,
                            HospitalId = 2,
                            Hostname = "ubuntu-hosp-a-db",
                            IpAddress = "192.168.1.40",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Ubuntu 22.04 LTS",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        },
                        new
                        {
                            Id = "agent-win-app-01",
                            AssetId = 3L,
                            ConfigId = 1L,
                            HospitalId = 2,
                            Hostname = "win-hosp-a-app",
                            IpAddress = "192.168.1.41",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Windows Server 2019",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        },
                        new
                        {
                            Id = "agent-win-his-02",
                            AssetId = 4L,
                            ConfigId = 1L,
                            HospitalId = 5,
                            Hostname = "win-hosp-b-his",
                            IpAddress = "192.168.1.50",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Windows Server 2022",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        },
                        new
                        {
                            Id = "agent-lnx-web-02",
                            AssetId = 5L,
                            ConfigId = 1L,
                            HospitalId = 5,
                            Hostname = "ubuntu-hosp-b-web",
                            IpAddress = "192.168.1.51",
                            LastSeenAt = new DateTime(2026, 7, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            OsInfo = "Ubuntu 20.04 LTS",
                            RegisteredAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "online"
                        });
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AgentConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartbeatIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonitoredLogsConfig")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("agent_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            HeartbeatIntervalSeconds = 10,
                            IsDefault = true,
                            MetricsIntervalSeconds = 30,
                            MonitoredLogsConfig = "[]",
                            Name = "Default Hospital Policy",
                            UpdatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        });
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AgentPolicy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnabledLogs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HeartbeatInterval")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetricsInterval")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ResponseEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("agent_policies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Standard monitor policy with responses enabled.",
                            EnabledLogs = "ProcessMonitor,FileIntegrity,NetworkMonitor",
                            HeartbeatInterval = 10,
                            MetricsInterval = 10,
                            Name = "Default Policy",
                            ResponseEnabled = true,
                            Version = 1
                        });
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("IncidentId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("RuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TelegramSent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TriggerEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IncidentId");

                    b.HasIndex("RuleId");

                    b.HasIndex("TriggerEventId");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AlertRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertSeverity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConditionExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelegramChatId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "EventType");

                    b.ToTable("alert_rules", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ResourceType");

                    b.HasIndex("Severity");

                    b.HasIndex("Success");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("TimestampUtc", "Severity")
                        .HasDatabaseName("IX_audit_logs_TimestampUtc_Severity");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.CollectorNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CollectorKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigurationVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConnectedAgents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSync")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QueueSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SharedSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectorKey")
                        .IsUnique();

                    b.ToTable("collector_nodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CollectorKey = "primary_key",
                            ConfigurationVersion = 1,
                            ConnectedAgents = 0,
                            Description = "Primary SOC Collector Node",
                            HospitalId = 0,
                            IPAddress = "127.0.0.1",
                            LastHeartbeat = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastSeen = new DateTime(2026, 7, 17, 9, 10, 34, 191, DateTimeKind.Utc).AddTicks(8516),
                            LastSync = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "HQ Data Center",
                            Name = "Primary Collector",
                            QueueSize = 0,
                            RulesVersion = 1,
                            SharedSecret = "32ac234d7a942bdbe88387389da17e11b2cbb577ee2d8c17d5841705a8629724",
                            Status = "Online",
                            Version = "1.2.0"
                        });
                });

            modelBuilder.Entity("OneSecurity.Server.Models.EnrollmentToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CollectorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxUses")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PolicyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Used")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CollectorId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("enrollment_tokens", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("hospitals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ROOT",
                            Name = "Hospital Tổng"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HOSP_A",
                            Name = "Hospital A",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "HOSP_A1",
                            Name = "Hospital A1",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "HOSP_A2",
                            Name = "Hospital A2",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 5,
                            Code = "HOSP_B",
                            Name = "Hospital B",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "HOSP_B1",
                            Name = "Hospital B1",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 7,
                            Code = "HOSP_B2",
                            Name = "Hospital B2",
                            ParentId = 5
                        });
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Incident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedByUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedByUserId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.InfrastructureAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Building")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Criticality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystemVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .HasColumnType("TEXT");

                    b.Property<long>("PolicyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectorId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.HasIndex("PolicyId");

                    b.ToTable("infrastructure_assets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssetType = "Server",
                            Building = "Main Building",
                            CollectorId = 1L,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Criticality = "High",
                            Department = "IT",
                            Description = "HIS Web Server",
                            Domain = "WORKGROUP",
                            HospitalId = 1,
                            Hostname = "DESKTOP-FC9F6G9",
                            IPAddress = "192.168.1.35",
                            OperatingSystem = "Windows",
                            OperatingSystemVersion = "Server 2022",
                            Owner = "sysadmin",
                            PolicyId = 1L,
                            Status = "Managed",
                            UpdatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            AssetType = "Server",
                            Building = "Server Room A",
                            CollectorId = 1L,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Criticality = "Critical",
                            Department = "Security",
                            Description = "Main Database Server",
                            Domain = "hospa.local",
                            HospitalId = 2,
                            Hostname = "ubuntu-hosp-a-db",
                            IPAddress = "192.168.1.40",
                            OperatingSystem = "Linux",
                            OperatingSystemVersion = "Ubuntu 22.04 LTS",
                            Owner = "dbadmin",
                            PolicyId = 1L,
                            Status = "Managed",
                            UpdatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3L,
                            AssetType = "Server",
                            Building = "Server Room A",
                            CollectorId = 1L,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Criticality = "High",
                            Department = "IT",
                            Description = "Application Gateway",
                            Domain = "hospa.local",
                            HospitalId = 2,
                            Hostname = "win-hosp-a-app",
                            IPAddress = "192.168.1.41",
                            OperatingSystem = "Windows",
                            OperatingSystemVersion = "Server 2019",
                            Owner = "sysadmin",
                            PolicyId = 1L,
                            Status = "Managed",
                            UpdatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4L,
                            AssetType = "Server",
                            Building = "Clinic B",
                            CollectorId = 1L,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Criticality = "High",
                            Department = "Medical",
                            Description = "Clinic Portal Host",
                            Domain = "hospb.local",
                            HospitalId = 5,
                            Hostname = "win-hosp-b-his",
                            IPAddress = "192.168.1.50",
                            OperatingSystem = "Windows",
                            OperatingSystemVersion = "Server 2022",
                            Owner = "clinicadmin",
                            PolicyId = 1L,
                            Status = "Managed",
                            UpdatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5L,
                            AssetType = "Server",
                            Building = "Clinic B",
                            CollectorId = 1L,
                            CreatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Criticality = "Medium",
                            Department = "Public Relations",
                            Description = "Public Website Host",
                            Domain = "hospb.local",
                            HospitalId = 5,
                            Hostname = "ubuntu-hosp-b-web",
                            IPAddress = "192.168.1.51",
                            OperatingSystem = "Linux",
                            OperatingSystemVersion = "Ubuntu 20.04 LTS",
                            Owner = "webadmin",
                            PolicyId = 1L,
                            Status = "Managed",
                            UpdatedAt = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("OneSecurity.Server.Models.MetricRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CpuUsagePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiskUsagePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("NetworkInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NetworkOutBytes")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RamUsagePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AgentId", "Timestamp")
                        .HasDatabaseName("IX_metric_records_agent_timestamp_desc");

                    b.ToTable("metric_records", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.ResponseAction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("IncidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("response_actions", (string)null);
                });

            modelBuilder.Entity("OneSecurity.Server.Models.SecurityEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Severity");

                    b.HasIndex("Timestamp");

                    b.HasIndex("AgentId", "Timestamp")
                        .HasDatabaseName("IX_security_events_agent_timestamp_desc");

                    b.ToTable("security_events", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSecurity.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Agent", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.InfrastructureAsset", "Asset")
                        .WithMany("Agents")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneSecurity.Server.Models.AgentConfig", "Config")
                        .WithMany("Agents")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneSecurity.Server.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId");

                    b.Navigation("Asset");

                    b.Navigation("Config");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Alert", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.Agent", "Agent")
                        .WithMany("Alerts")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSecurity.Server.Models.Incident", "Incident")
                        .WithMany("Alerts")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneSecurity.Server.Models.AlertRule", "Rule")
                        .WithMany("Alerts")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneSecurity.Server.Models.SecurityEvent", "TriggerEvent")
                        .WithMany()
                        .HasForeignKey("TriggerEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agent");

                    b.Navigation("Incident");

                    b.Navigation("Rule");

                    b.Navigation("TriggerEvent");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.ApplicationUser", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.EnrollmentToken", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.InfrastructureAsset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSecurity.Server.Models.CollectorNode", "Collector")
                        .WithMany()
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneSecurity.Server.Models.AgentPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Collector");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Hospital", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.Hospital", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Incident", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.ApplicationUser", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OneSecurity.Server.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.InfrastructureAsset", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.CollectorNode", "Collector")
                        .WithMany()
                        .HasForeignKey("CollectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OneSecurity.Server.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId");

                    b.HasOne("OneSecurity.Server.Models.AgentPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collector");

                    b.Navigation("Hospital");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.MetricRecord", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.Agent", "Agent")
                        .WithMany("MetricRecords")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.ResponseAction", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSecurity.Server.Models.ApplicationUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OneSecurity.Server.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OneSecurity.Server.Models.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OneSecurity.Server.Models.ApplicationUser", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Hospital");

                    b.Navigation("Incident");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.SecurityEvent", b =>
                {
                    b.HasOne("OneSecurity.Server.Models.Agent", "Agent")
                        .WithMany("SecurityEvents")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Agent", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("MetricRecords");

                    b.Navigation("SecurityEvents");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AgentConfig", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.AlertRule", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Hospital", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.Incident", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("OneSecurity.Server.Models.InfrastructureAsset", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
